Fix release workflow
canonical/juju-lint pull request #297
Opened 2024-09-27 03:31 UTC by samuelallan72

The check workflow uploads the snap,
which conflicts with uploading the snap from the release workflow. So we can reuse the built snap from the check workflow, saving needing to rebuild the snap,
and avoiding the conflict.

Based on work in https://github.com/canonical/dcgm-snap/pull/36

2024-09-27 04:53 UTC, jneo8 requested changes
Need information

2024-09-27 04:53 UTC, jneo8 commented on .github/workflows/release.yaml
> +          snap: ${{ env.SNAP_FILE }}
**question:** 

Why `steps.build.outputs.snap` not works?

2024-09-27 04:57 UTC, jneo8 commented on .github/workflows/release.yaml
> +          snap: ${{ env.SNAP_FILE }}
I found the answer from https://github.com/canonical/dcgm-snap/pull/36

2024-09-27 04:57 UTC, jneo8 submitted a review, later dismissed

2024-09-27 05:02 UTC, Pjack submitted a review, later dismissed

2024-09-27 07:50 UTC, jneo8 approved these changes

2024-09-30 06:44 UTC, Pjack approved these changes

2024-09-30 06:45 UTC, merged